import "./alerts.cy";
import "./autocomplete-dropdown-list.cy";
import "./checkboxes.cy";
import "./data-table.cy";
import "./datepicker.cy";
import "./contact-us.cy";
import "./radio-buttons.cy";
import "./mouse-actions.cy";
import "./traversing-elements.cy";
